package network

import (
	"fmt"
	"net"
)

// This is the mac address prefix for now.
// TODO: move this to global config.
const MACAddressPrefix = "02:AA"

/**
 * ARCHITECTURE NOTES:
 * - If mac is given: parse it and return it if it is valide
 * - If no, generate it from IP
 * - Validate the generated MAC string against net.ParseMAC before returning.
 * - Review HCL schema to decide if 'mac' should remain a user-definable field
 * or be strictly auto-generated by this utility.
 */

// func ResolveMACADDR(inputIP, MACADDR string) (string, error) {
// 	_, err := net.ParseMAC(MACADDR)
// 	if err != nil {
// 		return "", fmt.Errorf("invalid MAC prefix %q", MACADDR)
// 	}
// 	IP2MAC(inputIP)
// }

// IP2MAC derives a deterministic MAC address from an IPv4 address.
func IP2MAC(inputIP string) (string, error) {
	// Check MAC Address prefix validity
	_, err := net.ParseMAC(MACAddressPrefix + ":00:00:00:00")
	if err != nil {
		return "", fmt.Errorf("invalid MAC prefix %q", MACAddressPrefix)
	}

	// Check if inputIP is a valide IP address
	ip := net.ParseIP(inputIP)
	if ip == nil {
		return "", fmt.Errorf("not an IPv4 address: %q", inputIP)
	}

	// Extract IPv4 bytes (4 bytes)
	ipv4 := ip.To4()
	if ipv4 == nil {
		return "", fmt.Errorf("%q is not an IPv4 address", inputIP)
	}

	// %02X ensures two-digit uppercase hex (e.g., '0' becomes '00')
	// %02x for lowercase hex
	// We use %02x to keep the MAC address lowercase (standard in Linux/Go)
	return fmt.Sprintf("%s:%02x:%02x:%02x:%02x",
		MACAddressPrefix,
		ipv4[0], ipv4[1], ipv4[2], ipv4[3],
	), nil
}
